sudo: false
language: node_js
cache:
  yarn: true
notifications:
  email: false
node_js:
  - '12'
script:
  - yarn run lint
  - yarn run lint-docs
  # the test suite doesn't quite work on Travis because of the way Travis
  # mucks with repositories
  # - yarn run jest
after_success:
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
