sudo: false
language: node_js
cache:
  yarn: true
notifications:
  email: false
node_js:
  - '12'
script:
  - yarn run lint
  - yarn run lint-docs
  - yarn run cover
  - bash <(curl -s https://codecov.io/bash)
after_success:
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
